# Generated by Django 6.0 on 2026-06-17 09:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('average', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('position', models.PositiveIntegerField(default=0)),
                ('teacher_remark', models.TextField(blank=True)),
                ('principal_remark', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEWED', 'Reviewed'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('class_size', models.PositiveIntegerField(default=0)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.schoolclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.term')),
            ],
        ),
        migrations.CreateModel(
            name='PsychomotorTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handwriting', models.PositiveSmallIntegerField(default=0)),
                ('sports', models.PositiveSmallIntegerField(default=0)),
                ('creativity', models.PositiveSmallIntegerField(default=0)),
                ('report_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_cards.reportcard')),
            ],
        ),
        migrations.CreateModel(
            name='PrincipalComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('report_card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='report_cards.reportcard')),
            ],
        ),
        migrations.CreateModel(
            name='AffectiveTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punctuality', models.PositiveSmallIntegerField(default=0)),
                ('honesty', models.PositiveSmallIntegerField(default=0)),
                ('leadership', models.PositiveSmallIntegerField(default=0)),
                ('cooperation', models.PositiveSmallIntegerField(default=0)),
                ('report_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report_cards.reportcard')),
            ],
        ),
        migrations.CreateModel(
            name='ResultVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('report_card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='report_cards.reportcard')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ca_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('exam_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('grade', models.CharField(max_length=5)),
                ('remark', models.CharField(max_length=100)),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.classsubject')),
                ('report_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='report_cards.reportcard')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('report_card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='report_cards.reportcard')),
            ],
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
